### PR TITLE
Make a skeleton of the project

### PR DESCRIPTION
**Pull request by tanmaysachan**

### CODE REVIEW

**Comment by tanmaysachan** [comment]
Is this roughly what you wanted? I could further build along this.

**Comment by chalmerlowe** [comment]
@tanmaysachan Thanks for this submission.

i downloaded it and ran the server to test the basic functionality.

I have taken a quick look. I will not be able to provide feedback right away, but will get you some ideas and suggestions as soon as possible.

chalmer

**Comment by tanmaysachan** [comment]
It is obviously pretty dull at the moment, but I think i can add the functionalities you want(im still learning).

**Comment by tanmaysachan** [comment]
Thanks for the review! I'm still learning, and relatively new to django.

**Comment by chalmerlowe** [comment]
@tanmaysachan It has been a very busy month, my apologies. I spent about 20 minutes this morning 
 looking at your suggestions. Through the course of the day, I will also attempt to look at some of the other options that others have suggested with the goal of reaching some decisions on how the project should proceed.

**Pull request merged**
