### PR TITLE
Created Timer

### PR DESCRIPTION
**Pull request by flaredragon**

### CODE REVIEW

**Comment by chalmerlowe** [comment]
@flaredragon Thanks for tackling this piece of the project...
Here are some suggestions/requests:

- [x] apply a sans serif font
- [x] fix the load screen: it loaded with only two digits: `5:0` vs `5:00`
- [x] increase the font size to fill a typical laptop screen
- [x] center the text in the browser window (horizontally and vertically)
- [x] modify the color changes...
   -  [x] from 5 to 2 minutes, use green
   -  [x] from 2 to 1 minute, use yellow?
   -  [x] from 1 minute to 30 seconds use orange
   -  [x] from 30 seconds to end, use red
- [x] fix the blink >> it seemed to blink once at 10 seconds, but then did not blink until it reached 0 seconds
- [x] Add a reset/restart button
    - [x] Upon reset, the blinking doesn't stop and the colors jump back and forth between red and green, red and green.

Appreciate the hard work.

**Comment by flaredragon** [comment]
Quick Question should I remove the double click Reset Feature then?I've made the other changes as requested.

**Comment by chalmerlowe** [comment]
I missed the note in your comments in the issues that highlighted the presence of a "double click" reset feature.

There is no reason to remove it.

The 'problem' with it, if you will, is that it is not intuitive for me. There was nothing in the interface (or in my  common experience) where a "double click" results in a reset of an expired feature.

Thus... my comment on adding a button. Let me try out the new version and provide some feedback on next steps...

**Comment by flaredragon** [comment]
Yeah, I know I accidentally have double clicked on the reference site you gave me so I thought I would be required here also.
Sure, I'm waiting for the feedback!

**Comment by chalmerlowe** [comment]
Looks good.
See the checklist above regarding some quirks associated with the reset/the red/the green, etc.

**Comment by flaredragon** [comment]
Yeah damn, I had forgot to check the base case.All done now!
Please Review

**Pull request merged**
